### ISSUE TITLE
picforth doesn't work with recent versions of gforth

### ISSUE THREAD

**Issue by rswarbrick** [samueltardieu/picforth#1]
I first tried the version of GForth in Debian (0.7.0 + some Debian patches). "make interactive" worked, but the whole thing seems to hang with 100% CPU when you include either of the chip definitions (for example, this happens if you run "make all")

Next, I downloaded and compiled GForth from their master tree. This no longer hangs, but instead we get an assertion error. I think this is related to their change here https://github.com/earl/gforth-mirror/commit/67ac4e1944b7fe8ed589b91af3aa9bd207381d6c.

While I'm vaguely proficient with Factor, I don't know Forth yet and was hoping to learn some by porting picforth to the 16F1824, which I've been using. But this seems to be a weird "hosting Forth on Forth" issue that I don't yet know enough to work around. Is there an obvious solution?

**Comment by samueltardieu** [comment]
This has been fixed in PicForth 1.3 which has just been released. It now works with gforth 0.7.3.
