### ISSUE TITLE
Detect Forth language

### ISSUE THREAD

**Issue by larsbrinkhoff** [samueltardieu/picforth#2]
Hello,

Please do a push to the repository, to make GitHub detect it as Forth.

Thanks!

**Comment by samueltardieu** [comment]
Where do you see that it is not detected as Forth already?

**Comment by larsbrinkhoff** [comment]
It showed up in this search as F#:
http://github.com/search?q=language%3Afsharp+forth&type=Repositories

But now that you did a push, GitHub updated the language dectection.  It will now show up among other Forth repos here:
http://github.com/search?l=forth&q=stars%3A%3E1&s=updated

I'm working on increasing visibility of Forth on GitHub.

**Comment by samueltardieu** [comment]
Good catch indeed. Thanks!
